# Generated by Django 4.0.5 on 2022-06-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, unique=True)),
                ('Author', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('article_slug', models.SlugField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Article',
                'ordering': ['id'],
            },
        ),
    ]
